version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Send notification
          command: curl -i -X GET https://api.telegram.org/bot$TGTOKEN/sendMessage?chat_id=$CHATID&text="Job Finished"
